// default package
// Generated 24-ene-2017 11:31:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias implements java.io.Serializable {

	private int codc;
	private String nombrec;
	private String descripcion;
	private Set productoses = new HashSet(0);

	public Categorias() {
	}

	public Categorias(int codc, String nombrec, String descripcion) {
		this.codc = codc;
		this.nombrec = nombrec;
		this.descripcion = descripcion;
	}

	public Categorias(int codc, String nombrec, String descripcion, Set productoses) {
		this.codc = codc;
		this.nombrec = nombrec;
		this.descripcion = descripcion;
		this.productoses = productoses;
	}

	public int getCodc() {
		return this.codc;
	}

	public void setCodc(int codc) {
		this.codc = codc;
	}

	public String getNombrec() {
		return this.nombrec;
	}

	public void setNombrec(String nombrec) {
		this.nombrec = nombrec;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set productoses) {
		this.productoses = productoses;
	}

}
