// default package
// Generated 24-ene-2017 11:31:47 by Hibernate Tools 3.4.0.CR1

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int codp;
	private Categorias categorias;
	private String nombrep;
	private int tamano;
	private String dosifica;

	public Productos() {
	}

	public Productos(int codp, Categorias categorias, String nombrep, int tamano, String dosifica) {
		this.codp = codp;
		this.categorias = categorias;
		this.nombrep = nombrep;
		this.tamano = tamano;
		this.dosifica = dosifica;
	}

	public int getCodp() {
		return this.codp;
	}

	public void setCodp(int codp) {
		this.codp = codp;
	}

	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public String getNombrep() {
		return this.nombrep;
	}

	public void setNombrep(String nombrep) {
		this.nombrep = nombrep;
	}

	public int getTamano() {
		return this.tamano;
	}

	public void setTamano(int tamano) {
		this.tamano = tamano;
	}

	public String getDosifica() {
		return this.dosifica;
	}

	public void setDosifica(String dosifica) {
		this.dosifica = dosifica;
	}

}
